### ISSUE TITLE
create hook to measure memory usage

### ISSUE THREAD

**Issue by smoors** [EESSI/test-suite#170]
PR https://github.com/EESSI/docs/pull/262 introduces a convenient way to measure the memory usage of a reframe test via cgroups

we can take this a step further and make a hook that checks:
- if slurm is used
- if slurm is configured with cgroups:
```
scontrol show config |grep "task/cgroup"
TaskPlugin              = task/cgroup,task/affinity
```
- which version of cgroups is used (v1 or v2)
- location of the cgroup hierarchy:
```
scontrol show config |grep "CgroupMountpoint"
CgroupMountpoint        = /sys/fs/cgroup
```

**Comment by casparvl** [comment]
Would be great. I was thinking, since the depth of the cgroup dir is different on cgroups v1 and v2 (on v2, you have to go up 3 levels to get to the `job_[1-9]+` directory. We could even just cut off the result of `cat /proc/self/cpuset` at the level of the `job_[1-9]+` level. On cgroups v1, that's:

```
$ cat /proc/self/cpuset
/slurm/uid_8877/job_1569456/step_interactive
```
on cgroups v2, that's:

```
$ cat /proc/self/cpuset
/system.slice/slurmstepd.scope/job_242/step_interactive/user/task_0
```
I.e. if we regex match that to obtain
```
/slurm/uid_8877/job_1569456
```
or
```
/system.slice/slurmstepd.scope/job_242
```
respectively, we don't have to rely on that nesting depth to stay the same (who knows, it might not).
