### ISSUE TITLE
move logic out of the GROMACS test as much as possible for maximal reuse in future tests

### ISSUE THREAD

**Issue by smoors** [EESSI/test-suite#18]

**Comment by smoors** [comment]
i tried using the `RegressionMixin` class to do multiple inheritance, but it didn't work.
the reason is probably because `RegressionMixin` is not a regular `RegressionTest` class.
it does work for parameters, but i don't think it's worth to use it just for parameters.

i think the solution with regular functions in https://github.com/EESSI/test-suite/pull/26 is quite nice: it also allows reusing the logic while at the same time all the hooks are listed explicitly. as the adagium says: explicit is better than implicit :)

**Comment by casparvl** [comment]
Yeah, I kind of saw the mix-of-solutions coming. I was thinking it would be ok, since the really generic stuff would be 'just put it in once and forget'. But, this may be overly optimistic. So yeah, you may be right, it may be overly complex, and being explicit / not doing 'magic' stuff may indeed be preferable. 

Note that even if we go for the hooks solution right now, we could _still_ change later: if we find that a handful of hooks is reused in _every_ test, _and if we think we could really put them in and forget_, we can still put those hooks in a `RegressionMixin` class.

**Comment by satishskamath** [comment]
Having a standard set of hooks is fine by me. But it does not protect functions that are not supposed to be used by some other tests which inheritance makes sort of automatic. But it indeed leads to a complicated scenario if we need to move functions around if needed:
* General -> inheritance
* inheritance -> General
What @smoors suggested does make things less complicated.

**Comment by boegel** [comment]
The motivation by @smoors to avoid inheritance makes total sense, so let's go with that approach indeed, especially since that doesn't lock us in at all (as @casparvl mentioned)
